import type { Metadata } from "next";
import "./globals.css";
import StateLayout from "@/components/layouts/StateLayout";
import TokenLayout from "@/components/layouts/TokenLayout";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StateLayout>
          <TokenLayout>
            {children}
          </TokenLayout>
        </StateLayout>
      </body>
    </html>
  );
}
